### ISSUE TITLE
Finding orientation

### ISSUE THREAD

**Issue by Zumbalamambo** [yinguobing/head-pose-estimation#1]
How do I know if the head is looking towards the left or right or up or down?

**Comment by yinguobing** [comment]
Do you mean how the pose is estimated?

It is actually done by solving a PnP problem. There is a 3D model and 68 corresponding 2D points in image that could be used to estimate the pose. [This post](http://www.learnopencv.com/head-pose-estimation-using-opencv-and-dlib/) might be helpful.
