### ISSUE TITLE
heatmap landmark 网络模型

### ISSUE THREAD

**Issue by hochiang** [yinguobing/head-pose-estimation#14]
您好，看过您写的`人脸特征点检测`系列的博客后，深受启发。这个系列使用的是回归特征点的位置来完成特征点检测，特征点有些抖动。另外我注意到您尝试了使用 [heatmap](https://yinguobing.com/heat-map-based-facial-landmark-localization/) 的方法，在这个项目下面有对应的 `heatmap` 分支，我没有发现相应的模型以及训练代码，不知您是否方便提供网络模型以及训练代码。谢谢！

**Comment by yinguobing** [comment]
Hi @hochiang 
这只是一种猜想，结果并不理想，相关代码没有保留。

**Comment by hochiang** [comment]
好的，谢谢
