### ISSUE TITLE
Estimate head pose as vector of direction

### ISSUE THREAD

**Issue by YOUlfey** [yinguobing/head-pose-estimation#17]
How I can get the vector of heads direction? Is it possible? If I have translation and rotation vectors, and 68 facial landmarks, How I can get 3d vector of heads direction?

**Comment by yinguobing** [comment]
Landmarks are not necessary if you have already got the translation and rotation vector. Check this out:
https://github.com/yinguobing/image_utility/blob/7c808c78bf6f5ccedf1fbaa73e4f3c446318dda5/pts_tools.py#L391

**Comment by xnholidayyy** [comment]
你好，请问一下您的代码里面是不是没有将旋转向量转换成欧拉角呀？

**Comment by yinguobing** [comment]
@xnholidayyy 是的。

**Comment by xnholidayyy** [comment]
谢谢😊

**Comment by yinguobing** [comment]
Seems to be safe to close.
