### ISSUE TITLE
Error in running estimate_head_pose.py

### ISSUE THREAD

**Issue by JandyalaSasanka** [yinguobing/head-pose-estimation#27]
![issue](https://user-images.githubusercontent.com/43935001/79909251-493e2300-843a-11ea-8dc2-1e52c1cd709f.PNG)

This is the error!

**Comment by JandyalaSasanka** [comment]
Solve this please

**Comment by pirate-lofy** [comment]
I think it's relevant to tensorflow version
try to use tensorflow 1.15

**Comment by yinguobing** [comment]
Are you using Windows? 
This project does not support Windows.

**Comment by JandyalaSasanka** [comment]
Yes sir, I have used the windows version commit, thanks
