### ISSUE TITLE
Controlling mouse with headpose angle 

### ISSUE THREAD

**Issue by SaddamBInSyed** [yinguobing/head-pose-estimation#28]
Hi @yinguobing ,

Thanks for the great work.

I want to control my mouse move with my head pose angle . 
I need your advice on this?

thanks

**Comment by yinguobing** [comment]
I'm not familiar with mouse control, maybe more details could be helpful.

**Comment by SaddamBInSyed** [comment]
@yinguobing 

Thanks for your reply.

 I want to convert the headpose angles (pitch, yaw) into desktop pc screen coordinates ( e.g 1920*1080 resolution)

Due to covid19 problem, user don't want to touch the kiosk application instead they can use their head (pose) to control the kiosk/pc  mouse to click/scroll/move


Hope you get my requirement


Thank you.

**Comment by yinguobing** [comment]
Is it possible to post a screenshot of the application here?

I think most applications like this would use touch screens rather than a
mouse.

SaddamBinSyed <notifications@github.com>于2020年5月9日 周六上午1:51写道：

**Comment by SaddamBInSyed** [comment]
Hi.
I am trying to build the application similar to the below.

https://www.youtube.com/watch?v=_WipkZU2pzQ
(please have a look into the above)

but instead of hand gesture I want headpose gesture.

thanks

**Comment by SaddamBInSyed** [comment]
Highly appreciated your response on this.

**Comment by yinguobing** [comment]
I've watched the video. Have the author released the code? I have no experience of mouse control with python, and I think head pose could only provide directions of movement，not exact pixels the cursor moved.

**Comment by SaddamBInSyed** [comment]
I found a way to do this.
but thanks again
