### ISSUE TITLE
not an issue. Need help in translating the angles.

### ISSUE THREAD

**Issue by Gauravajariwal11** [yinguobing/head-pose-estimation#36]
Hi, 

Thanks to your model I was able to get angles and head pose of the person in the videos. I was also able to get pitch, yaw, and roll. 
For example: pitch: -5.14, yaw: -0.35, roll: 2.94
However I am not able to understand this. How do we define how much pitch makes the face look down or how much roll makes the person's face tilt to left or right? The numbers above dont make sense to begin with because but I used your code from [pts_tool.py](https://github.com/yinguobing/image_utility/blob/17726335d2ce64a3b799dc0b7416f40ff928f805/pts_tools.py#L394) to get pitch, yaw and roll. 

Can you please clarify a bit? 

Thanks.

**Comment by yinguobing** [comment]
The OpenCV documentation had provided a really good explanation of this topic here:
https://docs.opencv.org/4.4.0/d9/d0c/group__calib3d.html

Pay attention to the chapter: Detailed Description

**Comment by Gauravajariwal11** [comment]
Oh okay. I'll read it. Also, Can you please explain why you have divided pitch, roll, and yaw by 180 [here](https://github.com/yinguobing/image_utility/blob/17726335d2ce64a3b799dc0b7416f40ff928f805/pts_tools.py#L408)

**Comment by Gauravajariwal11** [comment]
Also, what research paper have you used? I wanted to go through that and understand how the values of pitch and roll work if that makes sense.

**Comment by yinguobing** [comment]
The angles are normalized before saving. What do you mean "how the values of pitch and roll work"? I don’t get it.

**Comment by Gauravajariwal11** [comment]
"How the values of pitch and roll work" ---  Let me explain my question. I mean to say when do we consider a head to make a significant movement?

For example- Let say, we get value of roll to be 5 degrees at a time "t." Now is that 5 degrees enough to make a statement saying that head nodded towards the left side? If the value of roll is 20 degrees then it's a significant difference and we can consider that head tilted to the left, but should insignificant angles like 5-10 degrees should mean the same?

**Comment by yinguobing** [comment]
I think a lot of experiments are required before we make this decision. Those angles are not very accurate as they are rough estimation from the face landmarks and a general 3D model. Higher value means larger pose, but it is up to the application to set the threshold of these values. Also, nodding, is a series of head movement and brings in another variable time. I currently do not have a good idea of how to define nod. Sorry about that.

**Comment by Gauravajariwal11** [comment]
No problem! Thanks a lot for replying!

**Comment by youjinChung** [comment]
> The angles are normalized before saving. What do you mean "how the values of pitch and roll work"? I don’t get it.

Hello @yinguobing,

does that mean actual degrees are the ones before normalized?

**Comment by yinguobing** [comment]
@youjinChung Yes, if I still remember it right.
