### ISSUE TITLE
no preview showing when using cam

### ISSUE THREAD

**Issue by youjinChung** [yinguobing/head-pose-estimation#39]
Hello @yinguobing,

For some reason, when I run estimate_head_pose.py, it runs good with video inputs but showing nothing with a camera input.
There is no error message on the console, and the camera light is on. 
I ran just a basic code, and it shows the cam preview well.
What I tried is just a basic code like this:
```
import numpy as np
import cv2

cap = cv2.VideoCapture(0)

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()

    # Our operations on the frame come here
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Display the resulting frame
    cv2.imshow('frame',gray)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()
```
I am trying to find the reason though, just wanted to check if you have any hint about this.

**Comment by youjinChung** [comment]
I manually checked line by line, and it seems the process freeze in the line of
```
facebox = box_queue.get()
```
but it is interesting that it still works with video input.

**Comment by yinguobing** [comment]
It's hard to tell. I would

1. check if the OS and libraries versions match those writen in README.
2. try running in single thread mode by removing multiprocess and queues.
3. since video file is OK, maybe replace the current camera with another one.

Good luck!

**Comment by youjinChung** [comment]
Thanks for your opinions @yinguobing,

It was the multiprocess problem, when I ran without them it worked fine. 
The former repo worked with my webcam well though.
Let me reply here when I find the solution.

-Youjin

**Comment by yinguobing** [comment]
Glad to hear that 😃
