### ISSUE TITLE
tf1 error: unable to open file error_msg = 'Is a directory'

### ISSUE THREAD

**Issue by Picocu** [yinguobing/head-pose-estimation#42]
![image_2021-03-25_10-30-43](https://user-images.githubusercontent.com/58878114/112423855-3a9c7200-8d55-11eb-93ce-05b9c28a5c5d.png)
I tried with python=3.5|3.6|3.7 and tf = 1.10|1.14 in ubuntu 20.04 and 18.04. Could you please help me out with this?

**Comment by yinguobing** [comment]
Could you please try TensorFlow 2?

**Comment by Picocu** [comment]
It is working fine in tf2, but I need tf1 impelementation since I need to combine it with my tf1 model.

**Comment by yinguobing** [comment]
The branch `tf1` may suits your needs.
But I have to remind you that TF1 is no longer supported in this repository. A switch to TF2 is strongly recommended.

**Comment by Picocu** [comment]
Yes, I am working with **tf1** branch and getting this error. Could you please guide me through this?
