### ISSUE TITLE
Training and adding another class ??

### ISSUE THREAD

**Issue by Abduoit** [yinguobing/head-pose-estimation#6]
Thanks for sharing your great work 

Can I replace the file `frozen_inference_graph.pb` with another one that I trained my model on. Or can I re-train it for another class besides face. 

Thanks ??

**Comment by yinguobing** [comment]
I think you can do either if it suits your needs. Also be awared that the 3D model should also be modified.

This post could be helpful: http://www.learnopencv.com/head-pose-estimation-using-opencv-and-dlib/

**Comment by devanandd8245** [comment]
I would like to know whether i can train my dataset and load it in the model file frozen_inference_graph.pb. Could you please help me with some steps to be followed for generating the frozen_inference_graph.pb model file.

**Comment by yinguobing** [comment]
This could be helpful: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py

**Comment by devanandd8245** [comment]
Please could you help me with steps to be followed as i am new to TensorFlow.

Steps to be followed is that what are the files to be created and how to place them in sequence

**Comment by devanandd8245** [comment]
I need the procedure to be followed for the training.
Kindly guide me with the steps to be followed for the training module.

**Comment by devanandd8245** [comment]
Could you send me the English version page as i am not able to understand the Chinese language

**Comment by yinguobing** [comment]
Sorry there is only Chinese version available. I'm afraid you have to try Google translate or, ask a friend  who happens to understand Chinese for help.

**Comment by yinguobing** [comment]
Closed. For model training please refer to the other repository: `cnn-facial-landmark`.
