### ISSUE TITLE
Training of landmarks

### ISSUE THREAD

**Issue by LingQiu** [yinguobing/head-pose-estimation#7]
Hello,
how to train the CNN model of landmarks? I find some information in the link [https://github.com/yinguobing/cnn-facial-landmark/blob/master/landmark.py](url). This is the code of training,right?

**Comment by yinguobing** [comment]
Yes, that is the training code I used.

LingQiu <notifications@github.com>于2018年7月6日 周五上午9:29写道：

**Comment by LingQiu** [comment]
Thanks for your reply. In addition, how to set the 3D Box in the method of `draw_annotation_box` of the `class PoseEstimator` , why are the 75 and 100?
Thank you.

**Comment by yinguobing** [comment]
The box size was totally a “magic number”. It is related to the 3D model
size. You can change it however you like.

LingQiu <notifications@github.com>于2018年7月6日 周五下午2:55写道：

**Comment by LingQiu** [comment]
Thank you. The detection of landmarks on our dataset  is not so good. The size of faces and type of dataset are part of reasons. What's more, whether the `rotation_vector`  can be represented by `Roll,Yaw,Pitch`?

**Comment by yinguobing** [comment]
I think it's possible but I do not know how to do that temporarily. You might find something helpful [here](https://docs.opencv.org/3.4.1/d9/d0c/group__calib3d.html#ga549c2075fac14829ff4a58bc931c033d).

**Comment by LingQiu** [comment]
In my opinion, there are three steps:

1.[https://docs.opencv.org/3.4.1/d9/d0c/group__calib3d.html#ga549c2075fac14829ff4a58bc931c033d](url)
`retval, rvec, tvec = cv.solvePnP(objectPoints, imagePoints, cameraMatrix, distCoeffs[, rvec[, tvec[, useExtrinsicGuess[, flags]]]])`
2.`dst, jacobian = cv.Rodrigues(src[, dst[, jacobian]])`, rvec->dst
3.[https://www.cnblogs.com/flyinggod/p/8144100.html](url). It's a Chinese blog.

I hope I am right.

**Comment by yinguobing** [comment]
你提到的这篇博客写的很清楚，学习了！

**Comment by LingQiu** [comment]
首先，非常感谢您的回复。没有认真读您的博客，很是惭愧。
其次，我一直对3D的角度表示框很疑惑，不知道3维点该如何初始化，在这个链接里[https://github.com/lincolnhard/head-pose-estimation](url), 初始值跟您代码里差别有些大，不知道是不是平均脸归一化后的结果？
再者，看您的关键点训练系列博客有提到TadasBaltrusaitis的openface，我最近也在试着训练其中的CEN模型，参数和数据都有原因吧，效果没有理想中的好，不知您有没有尝试过？
最后，多谢您的不吝赐教。

**Comment by LingQiu** [comment]
谢谢，我再尝试一下。

**Comment by LingQiu** [comment]
@encodingwaddles ,sorry, you can refer this link [https://github.com/natanielruiz/deep-head-pose](url)
