### ISSUE TITLE
Where is your model.txt from ? And how?

### ISSUE THREAD

**Issue by ailias** [yinguobing/head-pose-estimation#8]
I'm curious about where is your 3d world coordinate facial landmarks in model.txt from?And how? 
Curiously I find different implementation has different values， why?

**Comment by yinguobing** [comment]
It’s from OpenFace, as pointed out in the Readme file.
You can use any model points you find, as long as their orders are the same.

**Comment by yinguobing** [comment]
Seems to be safe to close.

**Comment by tyoungroy** [comment]
I got https://github.com/TadasBaltrusaitis/OpenFace/blob/master/lib/local/LandmarkDetector/model/pdms/In-the-wild_aligned_PDM_68.txt and check the coordinate parts of it is identical to the model.txt
